name: graph
description: A graph for the Collatz Sequence
homepage: https://github.com/Amplus2/collatz-collection

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  gviz: ^0.4.0

dev_dependencies:
  pedantic: ^1.11.0
