#!/usr/bin/env python3

from os import path
from sys import argv, stdin, stderr

if len(argv) < 4:
    print(f'usage: {argv[0]} <base> <title> <template>', file=stderr)
    exit(1)

template = path.join(path.dirname(__file__), '../html/templates', argv[3] + '.html')
with open(template, 'r') as f:
    print(f.read()
        .replace('%BASE%', argv[1])
        .replace('%TITLE%', argv[2])
        .replace('%BODY%', '\n'.join(stdin.readlines())))
