name: CI

on: push

jobs:
  gpzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rm -rf computer/ raw/ tools/ tmp/ .github/ .git/ README.md Makefile Makefile.in *.cc configure LICENSE
      - uses: actions/upload-artifact@v2
        with:
          name: gpzip.zip
          path: .
