name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./configure
      - run: make -j$(nproc) test
  gpzip:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install -y make python3 curl inkscape imagemagick graphviz clang lld-12
      - run: sudo ln -s /usr/bin/wasm-ld-12 /usr/bin/wasm-ld
      - run: curl -Lo dart.deb https://storage.googleapis.com/dart-archive/channels/stable/release/latest/linux_packages/dart_2.13.4-1_amd64.deb
      - run: sudo dpkg -i dart.deb
      - run: rm -f dart.deb
      - run: ./configure
      - run: make clean
      - run: make -j$(nproc) dist
      - uses: actions/upload-artifact@v2
        with:
          name: gpzip
          path: .
