name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./configure
      - run: make -j$(nproc) test
  gpzip:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - run: make dist
      - uses: actions/upload-artifact@v2
        with:
          name: gpzip
          path: .
