name: CI

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./configure
      - run: make -j$(nproc) test
  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install -y make python3 curl inkscape imagemagick graphviz qrencode clang lld-12 nodejs npm fonts-inter cargo
      - run: cargo install deno --locked
      - run: sudo ln -s /usr/bin/wasm-ld-12 /usr/bin/wasm-ld
      - run: curl -Lo /usr/share/fonts/truetype/Manjari.ttf 'https://github.com/google/fonts/raw/main/ofl/manjari/Manjari-Regular.ttf'
      - run: ./configure
      - run: make clean
      - run: make -j$(nproc) dist
      - run: ls -lah
      - uses: actions/upload-artifact@v2
        with:
          name: package
          path: dist/package.zip
