name: CI

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make -j$(nproc) test
  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt update
      - run: sudo apt install -y make python3 curl inkscape imagemagick graphviz qrencode clang lld-12 nodejs npm fonts-inter
      - run: curl -fsSL https://deno.land/x/install/install.sh | DENO_INSTALL=/usr/local sh
      - run: sudo ln -s /usr/bin/wasm-ld-12 /usr/bin/wasm-ld
      - run: curl -Lo /usr/share/fonts/truetype/Manjari.ttf 'https://github.com/google/fonts/raw/main/ofl/manjari/Manjari-Regular.ttf'
      - run: make -j$(nproc) dist
      - uses: actions/upload-artifact@v2
        with:
          name: package
          path: dist
